name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ['27.1', '28.2', '29.4', '30.1', 'snapshot']
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Emacs version
        run: emacs --version
      - name: Byte compile
        run: make compile
      - name: Run tests
        run: make test
      - name: Checkdoc
        run: make checkdoc

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: '30.1'
      - name: Install package-lint
        run: |
          emacs --batch \
            --eval "(require 'package)" \
            --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" \
            --eval "(package-initialize)" \
            --eval "(package-refresh-contents)" \
            --eval "(package-install 'package-lint)"
      - name: Package lint
        run: make package-lint
